api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
  file:
    filename: "./dynamic.yml"
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/fullchain.pem"
        keyFile: "/privkey.pem"

certificatesResolvers:
  letsencrypt:
    acme:
      email: bummy.suri.official@gmail.com
      storage: ./acme.json
      httpChallenge:
        entryPoint: web

